### ISSUE TITLE
Missing texture?

### ISSUE THREAD

**Issue by TurkeyMcMac** [Beanzilla/teleporter_tool#1]
When I use the contentdb version, there's an error and the tool texture doesn't load. A dummy texture gets used instead. I'm using the current Android version of Minetest.

**Comment by ApolloX939** [comment]
Hmm... Perhaps I missed something... will check.

- [x] Verify Texture is able to load with latest contentdb version. (New version 1.1, v1.0 has been removed to prevent players from getting a broken version)

**Comment by ApolloX939** [comment]
[v1.1](https://github.com/Beanzilla/teleporter_tool/releases/tag/v1.1)
